In [2]:
import pandas as pd
import numpy as np
from datetime import datetime, timedelta

In [3]:
def make_timedelta(df, col):
    df['seconds'] = df[col]
    df[col] = pd.to_timedelta(df[col], unit='s')

In [4]:
size = "250Mb"

prefixes = ["blast_default", "blast", "last", "lastz", "stellar", "dist_stellar", "valik"]
table_df = pd.DataFrame([0, 0.02, 0.04, 0.06, 0.08, 0.1])
for prefix in prefixes:
    df = pd.read_csv("simulated/" + size + "/" + prefix + "_table1.tsv", sep = "\t")
    table_df[prefix + "_time"] = pd.to_timedelta(df["search time (sec)"], unit = 's')
    table_df[prefix + "_missed"] = df["missed (%)"]

table_df

,0,blast_default_time,blast_default_missed,blast_time,blast_missed,last_time,last_missed,lastz_time,lastz_missed,stellar_time,stellar_missed,dist_stellar_time,dist_stellar_missed,valik_time,valik_missed
0,0.00,0 days 00:01:21.053000,0.000,0 days 00:00:56.385000,0.001,0 days 00:15:27.492000,1.0,0 days 10:56:42.715000,0.0,0 days 03:36:33.180000,0.0,0 days 00:08:58.485000,0.0,0 days 00:07:19.729000,0.001
1,0.02,0 days 00:01:20.339000,0.002,0 days 00:01:30.327000,0.000,0 days 00:15:33.837000,1.0,0 days 11:19:10.201000,0.0,0 days 00:46:05.957000,0.0,0 days 00:02:41.145000,0.0,0 days 00:01:51.844000,0.000
2,0.04,0 days 00:01:20.408000,0.035,0 days 00:04:11.188000,0.000,0 days 00:15:42.086000,1.0,0 days 10:59:09.587000,0.0,0 days 00:03:30.248000,0.0,0 days 00:00:45.556000,0.0,0 days 00:00:30.050000,0.000
3,0.06,0 days 00:01:20.159000,0.133,0 days 01:16:20.215000,0.000,0 days 00:20:06.112000,1.0,0 days 10:59:11.496000,0.0,0 days 03:56:37.314000,0.0,0 days 00:10:46.747000,0.0,0 days 00:00:38.425000,0.000
4,0.08,0 days 00:01:18.936000,0.298,0 days 05:29:32.902000,0.000,0 days 00:18:39.712000,1.0,0 days 12:00:31.287000,0.0,NaT,NaN,1 days 06:03:45.086000,0.0,0 days 00:03:03.810000,0.001
5,0.10,0 days 00:01:17.430000,0.482,0 days 12:00:00.136000,1.000,0 days 00:18:03.135000,1.0,0 days 10:59:09.932000,0.0,NaT,NaN,1 days 06:41:35.472000,0.0,0 days 00:03:07.689000,0.011